# Generated by Django 5.2.3 on 2026-03-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Jazz', 'Jazz'), ('HipHop', 'HipHop')], max_length=50)),
                ('duration_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Generating', 'Generating'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MusicPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Jazz', 'Jazz'), ('HipHop', 'HipHop')], max_length=50)),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Workout', 'Workout'), ('Relax', 'Relax'), ('Party', 'Party')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
