# Generated by Django 5.2.3 on 2026-03-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Jazz', 'Jazz'), ('Hiphop', 'Hiphop')], default='Rock', max_length=50)),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Workout', 'Workout'), ('Relax', 'Relax'), ('Party', 'Party')], default='Party', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'musicprompt',
            },
        ),
    ]
