# Generated by Django 5.2.3 on 2026-03-13 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('musicprompt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Jazz', 'Jazz'), ('Hiphop', 'Hiphop')], default='Rock', max_length=50)),
                ('duration_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Generating', 'Generating'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('music_prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_prompt', to='musicprompt.musicprompt')),
            ],
            options={
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='library.library')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='music.music')),
            ],
            options={
                'db_table': 'playlist',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='library',
            field=models.ManyToManyField(through='music.Playlist', to='library.library'),
        ),
    ]
