# Generated by Django 5.2.3 on 2026-04-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
